#include "game.hpp"

void MainGame::initstyle() {
    setStyleSheet(
        "* { color: black; }"
        "QMainWindow, *[bg=true] { background-color: #EED9E8; }"

        "#curtxt { padding: 8px; }"

        "IcoButton, QPushButton[fancy=true] {"
            "background-color: #8B81A2;"
            "color: white;"
            "padding: 4px;"
            "border-style: outset;"
            "border-width: 2px;"
            "border-radius: 12px;"
            "border-color: #7B738A;"
        "}"
        "IcoButton:pressed, QPushButton[fancy=true]:pressed {"
            "background-color: #756D93;"
            "border-style: inset;"
        "}"
        "QPushButton[backbtn=true] { border-radius: 18px; }"
        "QPushButton[tinybtn=true] {"
            "background-color: #BACBAF;"
            "border-color: #749360;"
            "padding: 4px;"
        "}"
        "QPushButton[tinybtn=true]:pressed { background-color: #90AB7E; }"
        "QPushButton[optbtn=true] {"
            "color: black;"
            "background-color: #EBBA6B;"
            "border-color: #AC884F;"
            "padding: 10px 18px;"
            "border-radius: 16px;"
        "}"
        "QPushButton[optbtn=true]:pressed { background-color: #C1954E; }"
        "QPushButton[current=true] {"
            "background-color: #E1F28F;"
            "border-color: #B2BE7A;"
        "}"
        "QPushButton[current=true]:pressed { background-color: #BAC875; }"

        "Spoiler QToolButton {"
            "background-color: #A0C4B5;"
            "border-radius: 4px;"
            "padding: 5px;"
            "border-style: outset;"
            "border-width: 2px;"
            "border-radius: 6px;"
            "border-color: #588D77;"
            "qproperty-lineColour: #555;"
            "qproperty-lineWidth: 3px;"
        "}"
        "Spoiler QScrollArea {"
            "background-color: #D7E6DF;"
            "border-style: solid;"
            "border-width: 2px;"
            "border-radius: 5px;"
            "border-color: #B2CDBA;"
        "}"
        "Spoiler QToolButton:pressed {"
            "background-color: #72A791;"
            "border-style: inset;"
        "}"

        "TaskBubble { background: transparent; }"
        "TaskBubble QLabel {"
            "border-style: outset;"
            "border-width: 2px;"
            "border-color: #666;"
        "}"
        "TaskBubble[pressed=true] QLabel { border-style: inset; }"
        "TaskBubble QLabel[bubble=top] {"
            "background-color: #DD8866;"
            "border-top-left-radius: 12px;"
            "border-top-right-radius: 12px;"
            "padding: 8px;" "padding-bottom: 4px;"
            "border-bottom: 0px;"
        "}"
        "TaskBubble[pressed=true] QLabel[bubble=top] { background-color: #BB6655; }"
        "TaskBubble QLabel[bubble=bot] {"
            "background-color: #CC66AA;"
            "border-bottom-left-radius: 12px;"
            "border-bottom-right-radius: 12px;"
            "padding: 8px;" "padding-top: 4px;"
            "border-top: 0px;"
        "}"
        "TaskBubble[pressed=true] QLabel[bubble=bot] { background-color: #AA4488; }"

        "QTextEdit, QLineEdit {"
            "border-style: solid;"
            "border-width: 2px;"
            "border-color: #888;"
            "border-radius: 6px;"
            "padding: 4px;"
        "}"
        "QTextEdit:focus, QLineEdit:focus {"
            "border-color: #555;"
        "}"
        "QLineEdit { border-radius: 12px; }"

        "QScrollBar {"
            "background: transparent;"
            "border: none;"
        "}"
        "QScrollBar:vertical {"
            "width: 6px;"
            "margin: 2px 0px 2px 0px;"
        "}"
        "QScrollBar:horizontal {"
            "height: 6px;"
            "margin: 0px 2px 0px 2px;"
        "}"
        "QScrollBar::handle {"
            "background: rgba(0, 0, 0, 90);"
            "border-radius: 3px;"
            "min-height: 24px;"
        "}"
        "QScrollBar::add-line, QScrollBar::sub-line {"
            "width: 0px; height: 0px;"
            "background: none;"
        "}"
    );
}
