#include "game.hpp"

void MainGame::initstyle() {
    setStyleSheet(
        "* { color: black; }"
        "QMainWindow { background-color: #DDD; }"

        "IcoButton, *[isbtn=true] {"
            "background-color: #CCAA55;"
            "color: white;"
            "border-radius: 4px;"
            "padding: 4px;"
            "border-style: outset;"
            "border-width: 2px;"
            "border-radius: 6px;"
            "border-color: #887755;"
        "}"
        "IcoButton:pressed, *[isbtn=true]:pressed {"
            "background-color: #997744;"
            "border-style: inset;"
        "}"

        "Spoiler QToolButton {"
            "background-color: #55CCBB;"
            "color: white;"
            "border-radius: 4px;"
            "padding: 5px;"
            "border-style: outset;"
            "border-width: 2px;"
            "border-radius: 6px;"
            "border-color: #448877;"
            "qproperty-lineColour: #555;"
            "qproperty-lineWidth: 3px;"
        "}"
        "Spoiler QToolButton:pressed {"
            "background-color: #339988;"
            "border-style: inset;"
        "}"

        "TaskBubble { background: transparent; }"
        "TaskBubble QLabel {"
            "border-style: outset;"
            "border-width: 2px;"
            "border-color: #666;"
        "}"
        "TaskBubble[pressed=true] QLabel { border-style: inset; }"
        "TaskBubble QLabel[bubble=top] {"
            "background-color: #DD8866;"
            "border-top-left-radius: 12px;"
            "border-top-right-radius: 12px;"
            "padding: 8px;" "padding-bottom: 4px;"
            "border-bottom: 0px;"
        "}"
        "TaskBubble[pressed=true] QLabel[bubble=top] { background-color: #BB6655; }"
        "TaskBubble QLabel[bubble=bot] {"
            "background-color: #CC66AA;"
            "border-bottom-left-radius: 12px;"
            "border-bottom-right-radius: 12px;"
            "padding: 8px;" "padding-top: 4px;"
            "border-top: 0px;"
        "}"
        "TaskBubble[pressed=true] QLabel[bubble=bot] { background-color: #AA4488; }"

        "QTextEdit {"
            "border-style: solid;"
            "border-width: 2px;"
            "border-color: #888;"
            "border-radius: 6px;"
            "padding: 4px;"
        "}"
        "QTextEdit:focus {"
            "border-color: #555;"
        "}"

        "QScrollBar {"
            "width: 6px;"
            "background: transparent;"
            "border: none;"
            "margin: 2px 0px 2px 0px;"
        "}"
        "QScrollBar::handle {"
            "background: rgba(0, 0, 0, 90);"
            "border-radius: 3px;"
            "min-height: 24px;"
        "}"
        "QScrollBar::add-line, QScrollBar::sub-line {"
            "height: 0px;"
            "background: none;"
        "}"
    );
}
