#include "help.hpp"

const QString TASK_HELP =
"<h1>Help</h1>"
    "<p><b>Most things in this app are up to you to decide how to use!</b> I can recommend you how I use the app and how the app works but I gave it enough flexibility for you to organise however you want!</p>"
    "<p><i>Press outside any popup to dismiss it</i></p>"
    "<h2>Categories</h2>"
        "<p>Categories are like folders for your tasks.</p>"
        "<p>If you want to order your categories you can prefix your categories with e.g. a character such as '!' or a number, because the categories are sorted in alphabetical order.</p>"
    "<h2>Star</h2>"
        "<p>The star icon next to a task is the toggle for marking a task as starred.</p>"
        "<p>This makes a task more likely to be suggested.</p>"
        "<p>The star button next to the Categories title displays all the tasks you've starred.</p>"
    "<h2>Tasks</h2>"
        "<h3>Importance</h3>"
            "<p>A task's importance not only determines how high it is placed in the task list and also is used when determining which task to suggest you.</p>"
        "<h3>Goals</h3>"
            "<p>This is where you put the end goals you want to achieve from this task.<p>"
            "<p>You can really put what whatever here because it's just a text box, but <i>please use full sentences using 'you' instead of 'I' because these will be read back to you in the conversation by Grapefruit as one sentence (and will also have punctuation added, so don't add any yourself)</i>.</p>"
            "<p>For example another way you could use this is to put in why you want to do the task (what about it makes you happy), e.g. 'You love seeing things you make come to life' or something. It's really up to you!</p>"
        "<h3>Qualities</h3>"
            "<p>These are a list of predefined qualities about the task that are also used to determine when to suggest you the task (e.g. not suggesting you 'complex' tasks when you are tired).</p>"
        "<h3>Task items</h3>"
            "<p>This is a list of todo list items. They should aim to be as short as possible (in length of time), and can have dates and estimated time assigned using the date picker in the bottom bar.</p>"
            "<p>The \"multi-checks in a repeat symbol\" icon means 'check this and all previous items'</p>"
            "<p>Checking an item makes it act as if it doesn't exist for task calculations. You can keep old completed tasks if you want or delete them, it's up to you.</p>"
;
