#include "help.hpp"

const QString TASK_HELP =
"<h1>Help</h1>"
    "<h2>Categories</h2>"
        "<p>Categories are like folders for your tasks. How you decide to categorise your tasks is entirely up to you!</p>"
        "<p>If you want to order your categories you can prefix your categories with e.g. a character such as '!' or a number, because the categories are sorted in alphabetical order.</p>"
    "<h2>Star</h2>"
        "<p>The star icon next to a task is the toggle for marking a task as starred.</p>"
        "<p>This makes a task more likely to be suggested.</p>"
        "<p>The star button next to the Categories title displays all the tasks you've starred.</p>"
    "<h2>Tasks</h2>"
        "<p>Press outside the task popup to dismiss it.</p>"
        "<h3>Importance</h3>"
            "<p>A task's importance not only determines how high it is placed in the task list and also is used when determining which task to suggest you.</p>"
        "<h3>Reasoning</h3>"
            "<p>This is where you put reasoning as to why you want to do the task!</p>"
            "<p><i>Please phrase these as sentences about yourself in second person, i.e. 'You ...' and do not include punctuation at the end.</i></p>"
            "<p>The best way to use this is by having intrinsically motivating reasons - <b>What do you enjoy about doing the task?</b></p>"
            "<p>For example, while you may want to put e.g. 'You want to do well at ...' it is more effective if you think about <i>why you want to do this in the first place</i>, e.g. 'You love seeing the things you build come to life'</p>"
        "<h3>Qualities</h3>"
            "<p>These are a list of predefined qualities about the task that are used to determine when to suggest you the task.</p>"
        "<h3>Task items</h3>"
            "<p>This is a list of todo list items. They should aim to be as short as possible (in length of time and how much there is to do), and can have dates assigned using the date picker in the bottom bar.</p>"
            "<p>The \"multi-checks in a repeat symbol\" icon means 'check this and all previous items'</p>"
            "<p>Checking an item makes it act as if it doesn't exist for task calculations. You can keep old completed tasks if you want or delete them, it's up to you.</p>"
;
