#include "help.hpp"

const QString TASK_HELP =
"<h1>Help</h1>"
    "<h2>Categories</h2>"
        "<p>Categories are like folders for your tasks. "
            "How you decide to categorise your tasks is up to you, for example you can put school/work related tasks in one and home tasks in another, or have one for hobbies, one for projects and one for important things - it is entirely for you to decide!</p>"
        "<p>If you want to order your categories you can prefix your categories with e.g. a character such as '!' or a number, because the categories are sorted in alphabetical order.</p>"
    "<h2>Tasks</h2>"
        "<p>A task is made up of multiple parts, as stated below.</p>"
        "<p>Press outside the popup to dismiss it.</p>"
        "<h3>Importance</h3>"
            "<p>A task's importance not only determines how high it is placed in the task list but also somewhat changes how much it is recommended to you</p>"
        "<h3>Reasoning</h3>"
            "<p>This is where you can put reasons why you want to do this!</p>"
            "<p><i>Please phrase these as sentences about yourself in second person, i.e. 'You ...'</i></p>"
            "<p>The best use of this is to have intrinsically motivational reasons instead of extrinsic motives. "
                "For example, while you may want to put e.g. 'You want to do well at ...' it is more effective if you evaluate <i>why you want to do this in the first place</i>, e.g. 'You love seeing things come to life'</p>"
        "<h3>Qualities</h3>"
            "<p>These are a list of predefined qualities about the task that will be somewhat used to determine when to suggest you the task.</p>"
        "<h3>Task items</h3>"
            "<p>This is a list of TODOs. They should aim to be as short as possible, and can have dates assigned using the date picker in the bottom bar.</p>"
            "<p>The multi-checks in a repeat symbol icon means 'check this and all previous items'</p>"
            "<p>You don't have to keep old finished items if you don't want to. "
                "Checking an item removes it from all calculations that will be done on the task, and it's nice to see your progress but don't feel bad about deleting them if there are too many or you don't want to see them or anything.</p>"
;
